"""Prompt assets for AgentOrchestra agents."""

from agentorchestra.prompts.manager import (
    MANAGER_AGENT_BACKSTORY,
    MANAGER_AGENT_GOAL,
    MANAGER_AGENT_ROLE,
    MANAGER_ROUTING_TASK_DESCRIPTION,
    MANAGER_ROUTING_TASK_EXPECTED_OUTPUT,
    MANAGER_SYSTEM_PROMPT,
)

__all__ = [
    "MANAGER_AGENT_BACKSTORY",
    "MANAGER_AGENT_GOAL",
    "MANAGER_AGENT_ROLE",
    "MANAGER_ROUTING_TASK_DESCRIPTION",
    "MANAGER_ROUTING_TASK_EXPECTED_OUTPUT",
    "MANAGER_SYSTEM_PROMPT",
]
